project9/urls.py
from django.contrib import admin
from django.urls import path,include
from generic.views import *
import specific

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bharu/',bharu,name='bharu'),
    path('kumari/',kumari,name='kumari'),
    path('specific/',include('specific.urls')),

] 

specific/urls.py
from django.urls import path
from specific.views import *

app_name ='specific'

urlpatterns = [
    path('nag/',nag,name='nag'),
    path('gani/',gani,name='gani')
]

generic/models.py
from django.db import models

# Create your models here.

specific/models.py
from django.db import models

# Create your models here.

generic/views.py
from django.shortcuts import render

# Create your views here.
def bharu(request):
    return render(request,'bharu.html')

def kumari(request):
    return render(request,'kumari.html')

specific/views.py
from django.shortcuts import render

# Create your views here.
def nag(request):
    return render(request,'nag.html')

def gani(request):
    return render(request,'gani.html')

templates/bharu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hi kumari how are you</h1>
        <a href="{% url 'kumari' %}"><h1>navigate to kumari</h1></a>
        <a href="{% url 'specific:nag' %}"><h1>navigate to nag</h1></a>
        <a href="{% url 'specific:gani' %}"><h1>navigate to gani</h1></a>
    </center>
</body>
</html>

templates/gani.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>I am fine nag what about you</h1>
    </center>
</body>
</html>

templates/kumari.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1><marquee>I am fine bharu what about you</marquee></h1>
    </center>
    
</body>
</html>

templates/nag.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hi gani how are you</h1>
    </center>
</body>
</html>